package com.kloudsense.drools;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class annotations implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.String summary;

    public annotations() {
    }

    public java.lang.String getSummary() {
        return this.summary;
    }

    public void setSummary(java.lang.String summary) {
        this.summary = summary;
    }

    public annotations(java.lang.String summary) {
        this.summary = summary;
    }

}